### ISSUE TITLE
MailHog cannot connect to mongo on Mac

### ISSUE THREAD

**Issue by MaksymSkrynnikov** [mailhog/MailHog#127] opened 2016-12-05 10:30 UTC
Configuring mailhog in docker-compose file as 
```
 mailhog:
    image: mailhog/mailhog
    depends_on:
      - mongo
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - dev-env
    environment:
      MH_STORAGE: mongodb
      MH_MONGO_URI: mongo:27017
```
It works on Linux and stores received messages to MongoDB(mailhog db, messages collection). 
On Mac (El Capitan 10.11.6)  cannot resolve address of container and getting
```
mailhog_1                    | 2016/12/05 10:29:44 Using MongoDB message storage
mailhog_1                    | 2016/12/05 10:29:44 Connecting to MongoDB: mongo:27017
mailhog_1                    | 2016/12/05 10:29:54 Error connecting to MongoDB: no reachable servers
mailhog_1                    | 2016/12/05 10:29:54 MongoDB storage unavailable, reverting to in-memory storage
mailhog_1                    | 2016/12/05 10:29:54 [SMTP] Binding to address: 0.0.0.0:1025
mailhog_1                    | [HTTP] Binding to address: 0.0.0.0:8025
mailhog_1                    | 2016/12/05 10:29:55 Serving under http://0.0.0.0:8025/
mailhog_1                    | Creating API v1 with WebPath:
mailhog_1                    | Creating API v2 with WebPath:
```

**Comment by z1lv1n4s** [comment] 2016-12-05 10:35
Can confirm had the same issue. It seems it may be related to GOlang. From inside the container mongo is reachable and can be pinged. Everything starts working fine if mongo hostname is replaced with an actual ip address.

**Comment by ian-kent** [comment] 2017-01-09 19:48
I'm not sure there'll be much I can do to help with this, but if you could let me know your docker and docker-compose versions I'll see if I can reproduce it.

As @z1lv1n4s says, it seems to be related to Go (or maybe specifically the mongodb driver) inside Docker containers. Had a bit of a dig around, and there's plenty of people complaining about similar issues.

Can you try running MailHog using the native binary from the [releases](https://github.com/mailhog/MailHog/releases/tag/v0.2.1) page, rather than using Docker - just wondering if that fixes it?

**Comment by oleksandr-fedorov** [comment] 2018-02-21 07:30
Seems, the mentioned issue occurs due to DNS resolve under corporate 
So such docker-compose config with VPN enabled causes issue:
` version: '2'
services:
mongo:
    image: *******/mongo:3.2
    ports:
      - "27017:27017"
  mailhog:
    image: mailhog/mailhog
    depends_on:
      - mongodb
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - "MH_STORAGE=mongodb"
      - "MH_MONGO_URI=mongo:27017"
`
Reason for this is that 'mongo' name is resolved to some corporate server:
`ping mongo
PING mongo.******.com (******) 56(84) bytes of data.`
with disabled VPN:
`ping mongo
ping: unknown host mongo`

So 2 solutions here:
1) disable vpn on using mailhog with 'mongo' named container
2) rename 'mongo' docker container to other name, e.g. 'mongodb' (no matter vpn enabled or not)
`    mongodb:
    image: ******/mongo:3.2
    ports:
      - "27017:27017"
mailhog:
    image: mailhog/mailhog
    depends_on:
      - mongodb
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - "MH_STORAGE=mongodb"
      - "MH_MONGO_URI=mongodb:27017"`

**Comment by tyndyll** [comment] 2019-02-19 10:03
Closing. This seems to be a user environment issue

**Closed by tyndyll** 2019-02-19 10:03 UTC
Labels: blocked
