### ISSUE TITLE
Message head in Web UI

### ISSUE THREAD

**Issue by bsbak** [mailhog/MailHog#147] opened 2017-03-29 11:31 UTC
In web UI message head is `{{ getSender(message) }}`, how change it to "name" \x6\6x7 madafaka

![screen](https://cloud.githubusercontent.com/assets/11431176/24452570/93aff45c-148c-11e7-8f8b-7c1b9e43aa8c.png)

**Comment by ian-kent** [comment] 2017-04-16 21:13
Hi @bsbak 

I can't reproduce it on the latest master branch (d4927bc7e6fc2c887b559e0b85f84dc2f5af3128) with any of my test messages.

Can you provide logs from MailHog, or the API response (e.g. from network tab on dev tools in chrome, or curl)? And check for any console log errors from the client UI javascript.

It looks like the From header in the message is missing, hasn't been parsed correctly, or getSender is throwing an exception, but its hard to tell without seeing the message data

**Comment by ian-kent** [comment] 2017-04-16 21:40
I think this is a duplicate of #144 - I'll close it for now, but please reopen if its a different issue

**Closed by ian-kent** 2017-04-16 21:40 UTC
Labels: blocked
